#!/usr/bin/perl -w

=head1 NAME

csvbankin

=head1 SYNOPSIS

parses csv bank statements and remembers account mappings

=cut

use strict;


=head1 MAIN PROGRAM FLOW

The program runs in two parts: read and write. Read is used to read in an input file and guess the account mappings. After the read sequence, the user checks the mappings in an intermediate file and adds new mappings B<csvbankin> doesn't know about yet. Then the write sequence is run, producing the final output file and saving the new account mappings to B<csvbankin's> account mapping file.

=cut


=head1 SUBROUTINES

=cut
